# This is a basic workflow that is manually triggered

name: CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
    - master
  
  push:
    branches:
    - master
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    # Runs a single command using the runners shell
    - name: CMake
      run: cmake -S . -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DSPVGENTWO_BUILD_TESTS=TRUE -DSPVGENTWO_BUILD_EXAMPLES=TRUE -DSPVGENTWO_BUILD_DISASSEMBLER=TRUE -DSPVGENTWO_BUILD_REFLECT=TRUE -DSPVGENTWO_BUILD_LINKER=TRUE
    
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Release -j4

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C Release
